echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
echo "Beginning update process ..."
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
echo "running git pull ... "
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
git pull
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
echo "Ran git pull."
echo "CubeBox updated from repository."
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――" 
echo "Running npm install." 
npm install
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
echo "Ran npm install."
echo "Node packages updated."
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
echo "Running 'pm2 restart cubebox.js.'"
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
pm2 restart cubebox.js
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
echo "Ran 'pm2 restart.cubebox.js'"
echo "CubeBox process restarted."
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"
echo "Update process complete. Please check above for errors."
echo "――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――"